### ISSUE TITLE
有没有办法导出群组笔记呢？

### ISSUE THREAD

**Issue by xuze1993** [awaken233/wiz2obsidian#1]
试了一下代码，好像只有个人笔记

**Comment by awaken233** [comment]
现有代码是默认读取个人笔记。要想导出群组笔记需要调整下代码，楼主可以尝试修改下代码。

https://github.com/awaken233/wiz2obsidian/blob/36fed5377033ab7653661a4d7980b916911e5f53/sync/wiz_open_api.py#L35-L42

这里默认设置的个人笔记的知识库 id。

**Comment by xuze1993** [comment]
> 现有代码是默认读取个人笔记。要想导出群组笔记需要调整下代码，楼主可以尝试修改下代码。
> 
> https://github.com/awaken233/wiz2obsidian/blob/36fed5377033ab7653661a4d7980b916911e5f53/sync/wiz_open_api.py#L35-L42
> 
> 这里默认设置的个人笔记的知识库 id。

请问下这些笔记类型是什么意思呢？我试着把群组的kbGuid直接赋值了，在note_synchronizer.py里90到114行出错了。可以查询到kb的信息，但是请求不到资源，看这段好像是在判断类型

**Comment by awaken233** [comment]
> > 现有代码是默认读取个人笔记。要想导出群组笔记需要调整下代码，楼主可以尝试修改下代码。
> > https://github.com/awaken233/wiz2obsidian/blob/36fed5377033ab7653661a4d7980b916911e5f53/sync/wiz_open_api.py#L35-L42
> > 
> > 这里默认设置的个人笔记的知识库 id。
> 
> 请问下这些笔记类型是什么意思呢？我试着把群组的kbGuid直接赋值了，在note_synchronizer.py里90到114行出错了。可以查询到kb的信息，但是请求不到资源，看这段好像是在判断类型

贴一下报错错误堆栈呢？

笔记类型随着为知的发展有：html 笔记，md 笔记，lite 笔记，协作笔记

群组笔记可能还需要去浏览器上抓包好好看下，和个人笔记的差异，调整代码？

**Comment by awaken233** [comment]
建议看下个人笔记的导出是否有问题？

**Comment by xuze1993** [comment]
第一个图是群组笔记的报错，第二个是个人笔记
个人笔记好像没问题，我这没图床简单试了下，没有其他报错，图片之类的资源已经下载到本地了

![图片](https://github.com/awaken233/wiz2obsidian/assets/35798540/75b7e4ef-6ee9-428e-b3e5-42d00925ad75)
![图片](https://github.com/awaken233/wiz2obsidian/assets/35798540/6b58bc5a-c25e-43f6-9309-ea1b0d95586c)

**Comment by xuze1993** [comment]
请求路径好像是一样的
![图片](https://github.com/awaken233/wiz2obsidian/assets/35798540/90433efd-9f7c-448e-8ea0-a65477d3c175)

**Comment by awaken233** [comment]
你的wiz 是私有化部署吗？ 看样子好像是获取协作笔记的内容使用的 wss:// 协议，socket.gaierror: [Errno -2] Name or service not known 解析地址失败？

**Comment by xuze1993** [comment]
> 你的wiz 是私有化部署吗？ 看样子好像是获取协作笔记的内容使用的 wss:// 协议，socket.gaierror: [Errno -2] Name or service not known 解析地址失败？

是私有化的，这个是一定需要域名吗？不过个人笔记为什么没啥问题呢

**Comment by awaken233** [comment]
简单改了一版代码，支持了群组笔记，conf.yaml 配置导出的群组名称即可。

这是我本地测试的效果：

<img width="1263" alt="image" src="https://github.com/awaken233/wiz2obsidian/assets/18060521/4a2e11b9-87d1-4a49-85e5-10fb0c0a0ec7">

**Comment by xuze1993** [comment]
> 简单改了一版代码，支持了群组笔记，conf.yaml 配置导出的群组名称即可。
> 
> 这是我本地测试的效果：
> <img alt="image" width="1263" src="https://private-user-images.githubusercontent.com/18060521/347474478-4a2e11b9-87d1-4a49-85e5-10fb0c0a0ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDQ4MzYsIm5iZiI6MTcyMDcwNDUzNiwicGF0aCI6Ii8xODA2MDUyMS8zNDc0NzQ0NzgtNGEyZTExYjktODdkMS00YTQ5LTg1ZTUtMTBmYjBjMGEwZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEzMjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTc2NjU2YzFjYWRjYThiZWFlYzI2MjhjMjJkN2JlYjFjNjkxNmIzMjljN2Y4OGM1NTQ1MmEwZmNjZTNhMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q0Vv7PPHC5N6NQuHBO9eA33a35vSNWoeK6oX0F85S-o">

我试了下新版本，也是能读到群组笔记但不能下载，报错是一样的。然后加了下本地解析，应该也不是dns的问题。上面这个是私有化的吗，感觉可能是私有化或者服务端版本不一样？ 依赖是websocket-client==1.3.1

**Comment by xuze1993** [comment]
> 建议升级一下版本，和项目中 requirements.txt 中的版本一致
> 
> 我看 [websocket-client/websocket-client#602](https://github.com/websocket-client/websocket-client/issues/602) 好像是类似的问题

没事了大佬，我想搭个新环境（同版本私有化），新环境群组新建了笔记加图片没问题。看来可能是我的笔记有问题 。
这个项目下载是只下载图片什么的吗，是不是不能下载附件之类的

**Comment by xuze1993** [comment]
> 建议升级一下版本，和项目中 requirements.txt 中的版本一致
> 
> 我看 [websocket-client/websocket-client#602](https://github.com/websocket-client/websocket-client/issues/602) 好像是类似的问题

我搭建了同版本的私有化服务端，然后新建了个群组笔记，插入附件，下载什么的都没问题。感觉可能是我原来的笔记有问题，因为它那个客户端老是升级，笔记类型和服务端好像也有点差别。也可能是多账户的问题？我自己再研究研究。
项目很有用，麻烦大佬了

**Comment by awaken233** [comment]
> > 建议升级一下版本，和项目中 requirements.txt 中的版本一致
> > 我看 [websocket-client/websocket-client#602](https://github.com/websocket-client/websocket-client/issues/602) 好像是类似的问题
> 
> 我搭建了同版本的私有化服务端，然后新建了个群组笔记，插入附件，下载什么的都没问题。感觉可能是我原来的笔记有问题，因为它那个客户端老是升级，笔记类型和服务端好像也有点差别。也可能是多账户的问题？我自己再研究研究。 项目很有用，麻烦大佬了

不用客气, 欢迎贡献代码, 程序还有很多不完善之处

**Comment by xuze1993** [comment]
> > 建议升级一下版本，和项目中 requirements.txt 中的版本一致
> > 我看 [websocket-client/websocket-client#602](https://github.com/websocket-client/websocket-client/issues/602) 好像是类似的问题
> 
> 我搭建了同版本的私有化服务端，然后新建了个群组笔记，插入附件，下载什么的都没问题。感觉可能是我原来的笔记有问题，因为它那个客户端老是升级，笔记类型和服务端好像也有点差别。也可能是多账户的问题？我自己再研究研究。 项目很有用，麻烦大佬了

我的环境最后的问题还是请求路径有差别，一个是domain我的要replace的是http，第二个wss改成ws。然后就没问题了。

**Comment by awaken233** [comment]
> > > 建议升级一下版本，和项目中 requirements.txt 中的版本一致
> > > 我看 [websocket-client/websocket-client#602](https://github.com/websocket-client/websocket-client/issues/602) 好像是类似的问题
> > 
> > 
> > 我搭建了同版本的私有化服务端，然后新建了个群组笔记，插入附件，下载什么的都没问题。感觉可能是我原来的笔记有问题，因为它那个客户端老是升级，笔记类型和服务端好像也有点差别。也可能是多账户的问题？我自己再研究研究。 项目很有用，麻烦大佬了
> 
> 我的环境最后的问题还是请求路径有差别，一个是domain我的要replace的是http，第二个wss改成ws。然后就没问题了。

噢噢噢 原来如此 👍🏻👍🏻👍🏻
